# This workflow will check for changed files, install Python dependencies and
# run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Tests

on:
  # run on each push to every branch of the repository but only on
  # pull requests to the 'master' and 'branch-*' branches
  push:
  pull_request:
    branches:
      - 'master'
      - 'branch-*'

jobs:
  build:
    name: 'Run tests with Python'
    runs-on: ubuntu-22.04
    strategy:
      # don't cancel running matrix tests when one test fails
      fail-fast: false
      matrix:
        # current supported Python versions
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v3
      with:
        # clone submodules as well
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip installation
      uses: actions/cache@v3
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-py_${{ matrix.python-version }}-${{ hashFiles('requirements.txt', 'tests/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-py_${{ matrix.python-version }}-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      # create the virtual environment
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r tests/requirements.txt

    - name: Test with pytest
      id: pytest_run
      run: |
        pip freeze
        python -b -m pytest -v --cov=privacyidea --cov-report=xml tests/
      env:
        # Output DeprecationWarnings only once
        PYTHONWARNINGS: "once::DeprecationWarning"

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.xml
